In [2]:
import numpy as np

In [47]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [25]:
len(a[a < 0])

4

2. How many positive numbers are there?

In [26]:
len(a[a > 0])

5

3. How many even positive numbers are there?

In [30]:
len(a[(a>0) & (a%2 == 0)])

3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [135]:
len((a+3)[a+3>0])

10

5. If you squared each number, what would the new mean and standard deviation be?

In [44]:
print((a**2).mean())
print((a**2).std())

74.0
144.0243035046516


6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [137]:
a_center = a - a.mean()
a_center

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

7. Calculate the z-score for each data point. Recall that the z-score is given by:

Z = (x − μ) / σ


In [58]:
a_zscore = a_center / a.std()
a_zscore

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [88]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum_of_a / len(a)

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = 1
for number in a:
    product_of_a = product_of_a * number 

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = [number ** 2 for number in a]
squares_of_a

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = [number for number in a if number % 2 != 0]
odds_in_a

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = [number for number in a if number % 2 == 0]
evens_in_a

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
   #-- then you have to use numpy

[2, 4, 6, 8, 10]

In [92]:
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [96]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

33

In [140]:
import numpy as np
array_b = np.array(b)

sum_of_b = array_b.sum()
sum_of_b

33

In [141]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [142]:
min_of_b = array_b.min()
min_of_b

3

In [ ]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


In [99]:
max_of_b = array_b.max()
max_of_b

8

In [ ]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))


In [100]:
mean_of_b = array_b.mean()
mean_of_b

5.5

In [ ]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [102]:
product_of_b = np.prod(array_b)
product_of_b

20160

In [ ]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


In [104]:
squares_of_b = array_b ** 2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


In [143]:
b = array_b
b[b%2!=0]

array([3, 5, 7])

In [ ]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)


In [144]:
b[b%2==0]

array([4, 6, 8])

In [ ]:
# Exercise 9 - print out the shape of the array b.

In [146]:
b.shape

(2, 3)

In [ ]:
# Exercise 10 - transpose the array b.

In [147]:
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [ ]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)


In [152]:
np.reshape(b,(1,6))

array([[3, 4, 5, 6, 7, 8]])

In [ ]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


In [149]:
np.reshape(b,(6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [158]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
 

In [159]:
# Exercise 1 - Find the min, max, sum, and product of c.
c = np.array(c)

In [109]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [110]:
# Exercise 3 - Determine the variance of c.
c.std() ** 2

6.666666666666666

In [111]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [112]:
# Exercise 5 - Transpose c and print out transposed result.
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [113]:
# Exercise 6 - Get the dot product of the array c with c.
c@c

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [154]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
np.sum(c.T * c)

261

In [161]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
np.prod(c.T * c)

131681894400

In [119]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [120]:
# Exercise 1 - Find the sine of all the numbers in d

In [124]:
d = np.array(d)
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [122]:
# Exercise 2 - Find the cosine of all the numbers in d

In [126]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d

In [127]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [ ]:
# Exercise 4 - Find all the negative numbers in d

In [128]:
d[d<0]

array([-90, -30, -45, -45])

In [ ]:
# Exercise 5 - Find all the positive numbers in d

In [129]:
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.

In [130]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [ ]:
# Exercise 7 - Determine how many unique numbers there are in d.

In [131]:
len(np.unique(d))

11

In [ ]:
# Exercise 8 - Print out the shape of d.

In [132]:
d.shape

(3, 6)

In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.

In [133]:
d.T

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [ ]:
# Exercise 10 - Reshape d into an array of 9 x 2

In [134]:
np.reshape(d,(9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])